ALTER TABLE shifts
    ADD COLUMN IF NOT EXISTS code VARCHAR(30) NULL,
    ADD COLUMN IF NOT EXISTS cross_day BIT NOT NULL DEFAULT b'0',
    ADD COLUMN IF NOT EXISTS break_minutes INT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS paid_break_minutes INT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS min_staff INT NOT NULL DEFAULT 1,
    ADD COLUMN IF NOT EXISTS max_staff INT NOT NULL DEFAULT 1,
    ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE';

ALTER TABLE work_schedules
    ADD COLUMN IF NOT EXISTS planned_start_at DATETIME NULL,
    ADD COLUMN IF NOT EXISTS planned_end_at DATETIME NULL,
    ADD COLUMN IF NOT EXISTS publish_status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    ADD COLUMN IF NOT EXISTS note VARCHAR(255) NULL,
    ADD COLUMN IF NOT EXISTS published_at DATETIME NULL,
    ADD COLUMN IF NOT EXISTS locked_at DATETIME NULL;
